### ISSUE TITLE
RHEL | Install GitLab GPG key fails on Centos7

### ISSUE THREAD

**Issue by jardilio** [samdoran/ansible-role-gitlab#14]
Having issues running from centos7 failing with:

TASK [samdoran.gitlab : RHEL | Install GitLab GPG key] *************************
fatal: [gitlab]: FAILED! => {"changed": false, "failed": true, "msg": "gpg: no valid OpenPGP data found.\ngpg: processing message failed: Unknown system error\n"}
        to retry, use: --limit @/tmp/tmpraUhbO/playbook.retry

Issue seems to be related to https://github.com/ansible/ansible-container/issues/729#issuecomment-339712378 

I solved by extending this role and adding a pre-task to install epel-release:

```
- name: RHEL | Install epel-release
  yum:
    name: epel-release
    state: latest
  when: ansible_os_family == 'RedHat'

- include_role:
    name: samdoran.gitlab
```
